// This file is part of the Rendering Engine project.
// Author: Alexander Obzherin <alexanderobzherin@gmail.com>
// Copyright (c) 2026 Alexander Obzherin
// Distributed under the terms of the zlib License. See LICENSE.md for details.

#pragma once

#include "actor_2d.hpp"

// Generated by RenderingEngine SDK tool.
// You may modify this file freely.
// You can create and attach Drawable2D based subobject elements like Rectangle2D, Sprite2D, TextBlock2D etc.
// See Rendering Engine API Documentation

using namespace rendering_engine;

namespace rendering_engine
{

}

namespace application
{

class MultilingualTextActor : public Actor2D
{
public:
	MultilingualTextActor(Scene& scene);

	void Initialize() override;

	void Update(float deltaTime) override;

private:
	void CreateHeaders();
	void CreateDescriptions();

private:
	const glm::vec4 mHeaderColor{ 1.0f, 1.0f, 1.0f, 1.0f };
	glm::vec4 mDescColor{ 1.0f, 1.0f, 1.0f, 1.0f };
};

} // namespace application