#include "multilingual_text_actor.hpp"
#include "create_actor_2d_subobject.hpp"
#include "scene_component_2d.hpp"
#include "scene.hpp"
#include "scene_manager.hpp"
#include "i_application.hpp"
#include "multilingual_text_content.hpp"
#include "utility.hpp"
#include "color_space.hpp"

using namespace rendering_engine;

// Generated by RenderingEngine SDK tool.
// You may modify this file freely.
// You can create and attach Drawable2D based subobject elements like Rectangle2D, Sprite2D, TextBlock2D etc.
// See Rendering Engine API Documentation

namespace application
{
MultilingualTextActor::MultilingualTextActor(Scene& scene)
	:
	Actor2D(scene)
{}

void MultilingualTextActor::Initialize()
{
	Actor2D::Initialize();

	bUpdateOnTick = false;

	mDescColor = { ColorSpace::SRGBToLinear(glm::vec3(0.165f, 0.624f, 0.816f)), 1.0f };

	CreateDescriptions();
	CreateHeaders();
}

void MultilingualTextActor::Update(float deltaTime)
{
	Actor2D::Update(deltaTime);
}

void MultilingualTextActor::CreateHeaders()
{
	const float screenWidth = static_cast<float>(GetScene().GetSceneManager().GetApplication()->GetScreenSettings().width);
	const float screenHeight = static_cast<float>(GetScene().GetSceneManager().GetApplication()->GetScreenSettings().height);
	const float top = -screenHeight / 2.0f;
	const float thirdPartWidth = screenWidth / 3.0f;
	const float leftColumnStart = 0.0f - (screenWidth / 2.0f);
	const float centerColumnStart = leftColumnStart + thirdPartWidth;
	const float rightColumnStart = leftColumnStart + (thirdPartWidth * 2.0f);

	const float padding = 110.0f;

	const float verticalSpacing = 110.0f;

	const float sideBlockTopPadding = -250.0f;
	const float centerBlockTopPadding = 50.0f;
	
	// Left column
	// English
	TextBlock2D::Properties tbPropHeaderEng;
	tbPropHeaderEng.fontName = "CormorantGaramond-Bold";
	tbPropHeaderEng.fontSize = 44.0f;
	auto tbHeader_Eng = CreateSubobject<TextBlock2D>(tbPropHeaderEng);
	tbHeader_Eng->GetTransform().AttachTo(&mRootComponent);
	tbHeader_Eng->SetText(header_Eng);
	tbHeader_Eng->SetTextColor(mHeaderColor);
	tbHeader_Eng->SetPosition(glm::vec2(
		leftColumnStart + padding,
		sideBlockTopPadding + verticalSpacing * 0.0f
	));

	// Russian
	TextBlock2D::Properties tbPropHeaderRus;
	tbPropHeaderRus.fontName = "vezitsacyrillic";
	tbPropHeaderRus.fontSize = 40.0f;
	auto tbHeader_Rus = CreateSubobject<TextBlock2D>(tbPropHeaderRus);
	tbHeader_Rus->GetTransform().AttachTo(&mRootComponent);
	tbHeader_Rus->SetText(header_Rus);
	tbHeader_Rus->SetTextColor(mHeaderColor);
	tbHeader_Rus->SetPosition(glm::vec2(
		leftColumnStart + padding, 
		sideBlockTopPadding + verticalSpacing * 1.0f
	));

	// Greek
	TextBlock2D::Properties tbPropHeaderGrk;
	tbPropHeaderGrk.fontName = "Arima-SemiBold";
	tbPropHeaderGrk.fontSize = 40.0f;
	auto tbHeader_Grk = CreateSubobject<TextBlock2D>(tbPropHeaderGrk);
	tbHeader_Grk->GetTransform().AttachTo(&mRootComponent);
	tbHeader_Grk->SetText(header_Grk);
	tbHeader_Grk->SetTextColor(mHeaderColor);
	tbHeader_Grk->SetPosition(glm::vec2(
		leftColumnStart + padding, 
		sideBlockTopPadding + verticalSpacing * 2.0f
	));

	// Center column
	// Chinese
	TextBlock2D::Properties tbPropHeaderChn;
	tbPropHeaderChn.fontName = "NotoSansSC-Medium";
	tbPropHeaderChn.fontSize = 40.0f;
	auto tbHeader_Chn = CreateSubobject<TextBlock2D>(tbPropHeaderChn);
	tbHeader_Chn->GetTransform().AttachTo(&mRootComponent);
	tbHeader_Chn->SetText(header_Chn);
	tbHeader_Chn->SetTextColor(mHeaderColor);
	tbHeader_Chn->SetPosition(glm::vec2(
		-(tbHeader_Chn->GetDimensions().x / 2.0f),
		centerBlockTopPadding + verticalSpacing * 0.0f
	));
	// Japanese
	TextBlock2D::Properties tbPropHeaderJpn;
	tbPropHeaderJpn.fontName = "NotoSansSC-Medium";
	tbPropHeaderJpn.fontSize = 40.0f;
	auto tbHeader_Jpn = CreateSubobject<TextBlock2D>(tbPropHeaderJpn);
	tbHeader_Jpn->GetTransform().AttachTo(&mRootComponent);
	tbHeader_Jpn->SetText(header_Jpn);
	tbHeader_Jpn->SetTextColor(mHeaderColor);
	tbHeader_Jpn->SetPosition(glm::vec2(
		-(tbHeader_Jpn->GetDimensions().x / 2.0f),
		centerBlockTopPadding + verticalSpacing * 1.0f
	));
	// Korean
	TextBlock2D::Properties tbPropHeaderKrn;
	tbPropHeaderKrn.fontName = "NotoSansKR-Medium";
	tbPropHeaderKrn.fontSize = 40.0f;
	auto tbHeader_Krn = CreateSubobject<TextBlock2D>(tbPropHeaderKrn);
	tbHeader_Krn->GetTransform().AttachTo(&mRootComponent);
	tbHeader_Krn->SetText(header_Krn);
	tbHeader_Krn->SetTextColor(mHeaderColor);
	tbHeader_Krn->SetPosition(glm::vec2(
		-(tbHeader_Krn->GetDimensions().x / 2.0f),
		centerBlockTopPadding + verticalSpacing * 2.0f
	));

	// Right column
	// Hebrew
	TextBlock2D::Properties tbPropHeaderHbr;
	tbPropHeaderHbr.fontName = "FrankRuhlLibre-Medium";
	tbPropHeaderHbr.fontSize = 42.0f;
	tbPropHeaderHbr.textShapeEnabled = true;
	auto tbHeader_Hbr = CreateSubobject<TextBlock2D>(tbPropHeaderHbr);
	tbHeader_Hbr->GetTransform().AttachTo(&mRootComponent);
	tbHeader_Hbr->SetText(header_Hbr);
	tbHeader_Hbr->SetTextColor(mHeaderColor);
	tbHeader_Hbr->SetPosition(glm::vec2(
		(screenWidth / 2.0f) - tbHeader_Hbr->GetDimensions().x - padding,
		sideBlockTopPadding + verticalSpacing * 0.0f
	));
	// Arabic
	TextBlock2D::Properties tbPropHeaderArb;
	tbPropHeaderArb.fontName = "Amiri-Regular";
	tbPropHeaderArb.fontSize = 46.0f;
	tbPropHeaderArb.textShapeEnabled = true;
	auto tbHeader_Arb = CreateSubobject<TextBlock2D>(tbPropHeaderArb);
	tbHeader_Arb->GetTransform().AttachTo(&mRootComponent);
	tbHeader_Arb->SetText(header_Arb);
	tbHeader_Arb->SetTextColor(mHeaderColor);
	tbHeader_Arb->SetPosition(glm::vec2(
		(screenWidth / 2.0f) - tbHeader_Arb->GetDimensions().x - padding,
		sideBlockTopPadding + verticalSpacing * 1.0f
	));
	// Aramaic
	TextBlock2D::Properties tbPropHeaderArmc;
	tbPropHeaderArmc.fontName = "NotoSansSyriac-Regular";
	tbPropHeaderArmc.fontSize = 39.0f;
	tbPropHeaderArmc.textShapeEnabled = true;
	auto tbHeader_Armc = CreateSubobject<TextBlock2D>(tbPropHeaderArmc);
	tbHeader_Armc->GetTransform().AttachTo(&mRootComponent);
	tbHeader_Armc->SetText(header_Armc);
	tbHeader_Armc->SetTextColor(mHeaderColor);
	tbHeader_Armc->SetPosition(glm::vec2(
		(screenWidth / 2.0f) - tbHeader_Armc->GetDimensions().x - padding,
		sideBlockTopPadding + verticalSpacing * 2.0f
	));
}

void MultilingualTextActor::CreateDescriptions()
{
	const float screenWidth = static_cast<float>(GetScene().GetSceneManager().GetApplication()->GetScreenSettings().width);
	const float screenHeight = static_cast<float>(GetScene().GetSceneManager().GetApplication()->GetScreenSettings().height);
	const float top = -screenHeight / 2.0f;
	const float thirdPartWidth = screenWidth / 3.0f;
	const float leftColumnStart = 0.0f - (screenWidth / 2.0f);
	const float centerColumnStart = leftColumnStart + thirdPartWidth;
	const float rightColumnStart = leftColumnStart + (thirdPartWidth * 2.0f);

	const float thirdPartHeight = screenHeight / 3.0f;
	const float row0 = top;
	const float row1 = top + thirdPartHeight;
	const float row2 = top + thirdPartHeight * 2;

	const float padding = 26.0f;

	// Text Rendering headers text blocks
	// Left column
	// English
	TextBlock2D::Properties tbPropDescEng;
	tbPropDescEng.fontName = "CormorantGaramond-Bold";
	tbPropDescEng.fontSize = 26.0f;
	tbPropDescEng.lineSpacingScale = 0.85f;
	auto tbDesc_Eng = CreateSubobject<TextBlock2D>(tbPropDescEng);
	tbDesc_Eng->GetTransform().AttachTo(&mRootComponent);
	tbDesc_Eng->SetText(featureDesc_Eng);
	tbDesc_Eng->SetTextColor(mDescColor);
	tbDesc_Eng->SetPosition(glm::vec2(
		leftColumnStart + padding, 
		row0 + tbPropDescEng.fontSize + padding
	));
	// Russian
	TextBlock2D::Properties tbPropDescRus;
	tbPropDescRus.fontName = "vezitsacyrillic";
	tbPropDescRus.fontSize = 22.0f;
	tbPropDescRus.lineSpacingScale = 1.1f;
	auto tbDesc_Rus = CreateSubobject<TextBlock2D>(tbPropDescRus);
	tbDesc_Rus->GetTransform().AttachTo(&mRootComponent);
	tbDesc_Rus->SetText(featureDesc_Rus);
	tbDesc_Rus->SetTextColor(mDescColor);
	tbDesc_Rus->SetPosition(glm::vec2(
		leftColumnStart + padding,
		row1 + tbPropDescRus.fontSize + 10.0f
	));
	// Greek
	TextBlock2D::Properties tbPropDescGrk;
	tbPropDescGrk.fontName = "Arima-SemiBold";
	tbPropDescGrk.fontSize = 21.0f;
	tbPropDescGrk.lineSpacingScale = 0.7f;
	auto tbDesc_Grk = CreateSubobject<TextBlock2D>(tbPropDescGrk);
	tbDesc_Grk->GetTransform().AttachTo(&mRootComponent);
	tbDesc_Grk->SetText(featureDesc_Grk);
	tbDesc_Grk->SetTextColor(mDescColor);
	tbDesc_Grk->SetPosition(glm::vec2(
		leftColumnStart + padding,
		row2 + tbPropDescGrk.fontSize - 20.0f
	));

	// Center column
	// Chinese
	TextBlock2D::Properties tbPropDescChn;
	tbPropDescChn.fontName = "NotoSansSC-Medium";
	tbPropDescChn.fontSize = 25.0f;
	tbPropDescChn.textAlign = TextAlign::Center;
	tbPropDescChn.lineSpacingScale = 1.2f;
	auto tbDesc_Chn = CreateSubobject<TextBlock2D>(tbPropDescChn);
	tbDesc_Chn->GetTransform().AttachTo(&mRootComponent);
	tbDesc_Chn->SetText(featureDesc_Chn);
	tbDesc_Chn->SetTextColor(mDescColor);
	tbDesc_Chn->SetPosition(glm::vec2(
		-(tbDesc_Chn->GetDimensions().x / 2.0f), 
		row0 + tbPropDescChn.fontSize + padding + 20.0f
	));
	// Japanese
	TextBlock2D::Properties tbPropDescJpn;
	tbPropDescJpn.fontName = "NotoSansSC-Medium";
	tbPropDescJpn.fontSize = 23.0f;
	tbPropDescJpn.textAlign = TextAlign::Center;
	auto tbDesc_Jpn = CreateSubobject<TextBlock2D>(tbPropDescJpn);
	tbDesc_Jpn->GetTransform().AttachTo(&mRootComponent);
	tbDesc_Jpn->SetText(featureDesc_Jpn);
	tbDesc_Jpn->SetTextColor(mDescColor);
	tbDesc_Jpn->SetPosition(glm::vec2(
		-(tbDesc_Jpn->GetDimensions().x / 2.0f), 
		row1 + tbPropDescJpn.fontSize + 30.0f
	));
	// Korean
	TextBlock2D::Properties tbPropDescKrn;
	tbPropDescKrn.fontName = "NotoSansKR-Medium";
	tbPropDescKrn.fontSize = 24.0f;
	tbPropDescKrn.textAlign = TextAlign::Center;
	auto tbDesc_Krn = CreateSubobject<TextBlock2D>(tbPropDescKrn);
	tbDesc_Krn->GetTransform().AttachTo(&mRootComponent);
	tbDesc_Krn->SetText(featureDesc_Krn);
	tbDesc_Krn->SetTextColor(mDescColor);
	tbDesc_Krn->SetPosition(glm::vec2(
		-(tbDesc_Krn->GetDimensions().x / 2.0f), 
		row2 + tbPropDescKrn.fontSize + 10.0f
	));

	// Right column
	// Hebrew
	TextBlock2D::Properties tbPropDescHbr;
	tbPropDescHbr.fontName = "FrankRuhlLibre-Medium";
	tbPropDescHbr.fontSize = 26.0f;
	tbPropDescHbr.textAlign = TextAlign::Right;
	tbPropDescHbr.textShapeEnabled = true;
	auto tbDesc_Hbr = CreateSubobject<TextBlock2D>(tbPropDescHbr);
	tbDesc_Hbr->GetTransform().AttachTo(&mRootComponent);
	tbDesc_Hbr->SetText(featureDesc_Hbr);
	tbDesc_Hbr->SetTextColor(mDescColor);
	tbDesc_Hbr->SetPosition(glm::vec2(
		(screenWidth / 2.0f) - tbDesc_Hbr->GetDimensions().x - padding,
		row0 + tbPropDescHbr.fontSize + padding + 10.0f
	));
	// Arabic
	TextBlock2D::Properties tbPropDescArb;
	tbPropDescArb.fontName = "Amiri-Bold";
	tbPropDescArb.fontSize = 26.0f;
	tbPropDescArb.textAlign = TextAlign::Right;
	tbPropDescArb.textShapeEnabled = true;
	auto tbDesc_Arb = CreateSubobject<TextBlock2D>(tbPropDescArb);
	tbDesc_Arb->GetTransform().AttachTo(&mRootComponent);
	tbDesc_Arb->SetText(featureDesc_Arb);
	tbDesc_Arb->SetTextColor(mDescColor);
	tbDesc_Arb->SetPosition(glm::vec2(
		(screenWidth / 2.0f) - tbDesc_Arb->GetDimensions().x - padding,
		row1 + tbPropDescArb.fontSize
	));
	// Aramaic
	TextBlock2D::Properties tbPropDescArmc;
	tbPropDescArmc.fontName = "NotoSansSyriac-Medium";
	tbPropDescArmc.fontSize = 21.0f;
	tbPropDescArmc.textAlign = TextAlign::Right;
	tbPropDescArmc.textShapeEnabled = true;
	auto tbDesc_Armc = CreateSubobject<TextBlock2D>(tbPropDescArmc);
	tbDesc_Armc->GetTransform().AttachTo(&mRootComponent);
	tbDesc_Armc->SetText(featureDesc_Armc);
	tbDesc_Armc->SetTextColor(mDescColor);
	tbDesc_Armc->SetPosition(glm::vec2(
		(screenWidth / 2.0f) - tbDesc_Armc->GetDimensions().x - padding,
		row2 + tbPropDescArmc.fontSize + 20.0f
	));
}

} // namespace application
