#!/usr/bin/env python3
# This file is part of the Rendering Engine project.
# Author: Alexander Obzherin <alexanderobzherin@gmail.com>
# Copyright (c) 2026 Alexander Obzherin
# Distributed under the terms of the zlib License. See LICENSE.md for details.
##
"""
@file package_project.py
@brief Packages a built Rendering Engine application into a distributable layout.

Usage:
    python3 package_project.py
    python3 package_project.py --packed
    python3 package_project.py --packed --keep-plain

Packaging modes:

  • Default (no arguments)
        Copies Content/ as loose files and folders.
        Produces the package:
            <Build>/<App>/Packages/<App>-vX.Y.Z-<Platform>/

  • --packed
        Packs all assets from Content/ into:
            Content/Pack.bin
            Content/Pack.json
        Removes loose folders unless --keep-plain is also provided.

  • --packed --keep-plain
        Generates Pack.bin/Pack.json but preserves original loose assets.
        Useful for debugging or verification.

Both Windows and Unix platforms are supported.
The resulting package folder is also archived as a ZIP.
"""

import os
import shutil
import sys
import re
import datetime
import subprocess
import json

# --------------------------------------------------------------------------------------
# Helpers
# --------------------------------------------------------------------------------------

def detect_platform():
    p = sys.platform
    if p.startswith("win"):
        return "Windows"
    elif p.startswith("linux"):
        return "Linux"
    elif p.startswith("freebsd"):
        return "FreeBSD"
    return "Unknown"


def copy_tree(src, dst):
    if not os.path.exists(src):
        print(f"[WARN] Missing folder: {src}")
        return
    if os.path.exists(dst):
        shutil.rmtree(dst)
    shutil.copytree(src, dst)
    print(f"[COPY] {src} -> {dst}")


def ensure_dir(path):
    os.makedirs(path, exist_ok=True)
    return path


def read_version(project_root):
    """
    Try to read version.h generated by engine OR fallback to 0.0.0
    """
    possible_paths = [
        os.path.join(project_root, "..", "..", "Build", "Intermediate", "Generated", "version.h"),
        os.path.join(project_root, "..", "..", "Build", "Installed", "RenderingEngine",
                     "RenderingLibrary", "Include", "version.h")
    ]

    for p in possible_paths:
        if os.path.isfile(p):
            with open(p, "r", encoding="utf-8") as f:
                txt = f.read()
            major = re.search(r"RENDERING_ENGINE_VERSION_MAJOR\s+(\d+)", txt)
            minor = re.search(r"RENDERING_ENGINE_VERSION_MINOR\s+(\d+)", txt)
            patch = re.search(r"RENDERING_ENGINE_VERSION_PATCH\s+(\d+)", txt)
            if major and minor and patch:
                return f"{major.group(1)}.{minor.group(1)}.{patch.group(1)}"

    return "0.0.0"


def write_manifest(dst_dir, project_name, version, platform_name):
    manifest = os.path.join(dst_dir, "Manifest.txt")
    with open(manifest, "w", encoding="utf-8") as f:
        f.write(f"Rendering Engine Application Package\n")
        f.write(f"=================================\n\n")
        f.write(f"Project : {project_name}\n")
        f.write(f"Version : {version}\n")
        f.write(f"Platform: {platform_name}\n")
        f.write(f"Date    : {datetime.datetime.now()}\n\n")
        f.write("Folder layout:\n")
        f.write("  Binaries/            : executable + required DLLs/.so\n")
        f.write("  Content/             : shaders, textures, models, fonts\n")
        f.write("  Config/              : config files\n")
        f.write("  Logs/                : runtime logs (empty)\n")
    print(f"[OK] Manifest written: {manifest}")

def find_build_root(project_root, project_name):
    """
    Handle both DevMode and SDK-user layout:

    DevMode:
      <repo_root>/TestApplications/<ProjectName>/
      <repo_root>/Build/TestApplications/<ProjectName>/

    SDK-user:
      <sdk_root>/ContentExamples/<ProjectName>/
      <sdk_root>/Build/UserApplications/<ProjectName>/
    """
    candidates = [
        os.path.join(project_root, "..", "..", "Build", "TestApplications", project_name),
        os.path.join(project_root, "..", "..", "Build", "UserApplications", project_name),
    ]

    for c in candidates:
        if os.path.isdir(c):
            return os.path.abspath(c)

    return None

# --------------------------------------------------------------------------------------
# Windows-specific dependency handling
# --------------------------------------------------------------------------------------


def find_vulkan_loader_windows():
    """
    Try to locate a redistributable vulkan-1.dll on Windows.
    Priority:
      1. VULKAN_SDK/Redistributable*/Bin*/vulkan-1.dll
      2. VULKAN_SDK/Bin*/vulkan-1.dll
      3. Any vulkan-1.dll found on PATH
    """
    vulkan_sdk = os.environ.get("VULKAN_SDK", None)
    candidates = []

    if vulkan_sdk:
        # Common redistributable layouts
        for sub in [
            "Redistributable\\Bin",
            "Redistributable\\Bin32",
            "Redistributable\\Bin64",
            "Bin",
            "Bin32",
            "Bin64",
        ]:
            candidates.append(os.path.join(vulkan_sdk, sub, "vulkan-1.dll"))

    # Also search PATH directories (last resort)
    for path_dir in os.environ.get("PATH", "").split(os.pathsep):
        if not path_dir:
            continue
        candidates.append(os.path.join(path_dir, "vulkan-1.dll"))

    for c in candidates:
        if os.path.isfile(c):
            return os.path.abspath(c)

    return None


def bundle_windows_dependencies(bin_dst):
    """
    Ensure that Vulkan loader is present in Binaries on Windows.
    """
    target_vulkan = os.path.join(bin_dst, "vulkan-1.dll")
    if os.path.isfile(target_vulkan):
        # Already present (e.g., copied from binary directory)
        print("[INFO] vulkan-1.dll already present in package.")
        return

    src = find_vulkan_loader_windows()
    if src:
        shutil.copy2(src, target_vulkan)
        print(f"[COPY] Vulkan loader: {src} -> {target_vulkan}")
    else:
        print("[WARN] Could not locate redistributable vulkan-1.dll. "
              "Target machine must have Vulkan runtime installed.")

# --------------------------------------------------------------------------------------
# Unix-specific dependency handling
# --------------------------------------------------------------------------------------


def is_system_lib_unix(path):
    """
    Heuristic filter for system libraries vs. 3rd-party libs on Unix.

    We treat libs under:
      /lib, /lib64, /usr/lib, /usr/lib64
    as system libraries (not copied).

    Anything under /usr/local, /opt, or engine/project-specific paths
    is treated as 3rd-party and copied.
    """
    if not path or not path.startswith("/"):
        return True  # non-absolute or weird: ignore

    real = os.path.realpath(path)
    system_prefixes = ("/lib", "/lib64", "/usr/lib", "/usr/lib64")

    return any(real.startswith(p) for p in system_prefixes)


def collect_unix_shared_libs(executable, dst_dir):
    """
    Run ldd on the executable and copy non-system shared libraries
    into dst_dir. This helps make the package more self-contained.
    """
    try:
        output = subprocess.check_output(["ldd", executable], text=True)
    except Exception as e:
        print(f"[WARN] Failed to run ldd on {executable}: {e}")
        return

    seen = set()

    for line in output.splitlines():
        line = line.strip()
        if not line:
            continue

        # Patterns:
        #   libX.so.1 => /path/to/libX.so.1 (0x...)
        #   /lib64/ld-linux-x86-64.so.2 (0x...)
        lib_path = None

        if "=>" in line:
            parts = line.split("=>", 1)
            right = parts[1].strip()
            if right == "not found":
                continue
            # right: "/path/to/lib.so (0xaddr)"
            if " " in right:
                candidate = right.split(" ", 1)[0]
            else:
                candidate = right
            if candidate.startswith("/"):
                lib_path = candidate
        else:
            # direct path form: "/lib64/ld-linux-x86-64.so.2 (0x...)"
            if line.startswith("/"):
                if " " in line:
                    candidate = line.split(" ", 1)[0]
                else:
                    candidate = line
                lib_path = candidate

        if not lib_path:
            continue

        lib_path = os.path.realpath(lib_path)

        # Filter out system libs
        if is_system_lib_unix(lib_path):
            continue

        if lib_path in seen:
            continue

        seen.add(lib_path)

        if not os.path.isfile(lib_path):
            continue

        dest = os.path.join(dst_dir, os.path.basename(lib_path))
        if not os.path.isfile(dest):
            shutil.copy2(lib_path, dest)
            print(f"[COPY] Unix shared lib: {lib_path} -> {dest}")


# --------------------------------------------------------------------------------------
# PACKED ASSET SUPPORT
# --------------------------------------------------------------------------------------

def pack_assets(source_content, final_content, keep_plain=False):
    """
    Creates:
      Content/Pack.bin
      Content/Pack.json

    The folder `final_content` already exists inside the package.
    `source_content` is the folder from your build area.
    """
    pack_bin = os.path.join(final_content, "Pack.bin")
    pack_json = os.path.join(final_content, "Pack.json")

    print("[INFO] Packing assets into Pack.bin...")

    manifest = {}
    offset = 0

    with open(pack_bin, "wb") as fout:
        for root, dirs, files in os.walk(source_content):
            for f in files:
                abs_path = os.path.join(root, f)
                rel_path = os.path.relpath(abs_path, source_content).replace("\\", "/")

                size = os.path.getsize(abs_path)

                # append data
                with open(abs_path, "rb") as fin:
                    fout.write(fin.read())

                manifest[rel_path] = {"offset": offset, "size": size}
                offset += size

    # Write JSON manifest
    with open(pack_json, "w", encoding="utf-8") as jf:
        json.dump(manifest, jf, indent=4)

    print(f"[INFO] Packed {len(manifest)} files into Pack.bin")

    # Clean up plain assets
    if not keep_plain:
        for item in os.listdir(final_content):
            p = os.path.join(final_content, item)
            if os.path.isdir(p):
                shutil.rmtree(p)
        print("[INFO] Removed loose asset directories (only Pack.bin remains).")


# --------------------------------------------------------------------------------------
# Main
# --------------------------------------------------------------------------------------

import argparse

def main():
    parser = argparse.ArgumentParser(description="Rendering Engine Project Packager")
    parser.add_argument(
        "--packed",
        action="store_true",
        help="Pack all assets into Content/Pack.bin instead of copying loose files."
    )
    parser.add_argument(
        "--keep-plain",
        action="store_true",
        help="Keep loose asset files when --packed is used."
    )
    args = parser.parse_args()

    project_root = os.path.abspath(os.getcwd())
    project_name = os.path.basename(project_root)

    print("=============================================")
    print(f" Packaging project: {project_name}")
    print("=============================================")

    # Detect platform
    plat = detect_platform()
    print(f"[INFO] Platform: {plat}")

    build_root = find_build_root(project_root, project_name)
    if not build_root:
        print("[ERROR] Could not locate build directory for project.")
        print("Expected one of:")
        print("  ../../Build/TestApplications/<ProjectName>")
        print("  ../../Build/UserApplications/<ProjectName>")
        return

    build_release = os.path.join(build_root, "Release")
    build_debug = os.path.join(build_root, "Debug")

    if not os.path.isdir(build_release) and not os.path.isdir(build_debug):
        print("[ERROR] No built artifacts found.")
        print("Build your project first:")
        if plat == "Windows":
            print("    build_project.bat")
        else:
            print("    ./build_project.sh")
        return

    # Choose Release if possible
    binary_dir = build_release if os.path.isdir(build_release) else build_debug
    print(f"[INFO] Using binary directory: {binary_dir}")

    # Detect executable
    exe = None
    for f in os.listdir(binary_dir):
        full_path = os.path.join(binary_dir, f)
        if plat == "Windows" and f.lower().endswith(".exe"):
            exe = f
            break
        if plat in ("Linux", "FreeBSD"):
            # Executable file without extension or with any name
            if os.path.isfile(full_path) and os.access(full_path, os.X_OK):
                exe = f
                break

    if exe is None:
        print("[ERROR] Could not find executable in", binary_dir)
        return

    print(f"[INFO] Found executable: {exe}")

    # Version
    version = read_version(project_root)
    print(f"[INFO] Version: {version}")

    # Output package directory
    package_root = os.path.join(build_root, "Packages")
    ensure_dir(package_root)

    out_dir_name = f"{project_name}-v{version}-{plat}"
    out_dir = os.path.join(package_root, out_dir_name)
    if os.path.exists(out_dir):
        shutil.rmtree(out_dir)

    print(f"[INFO] Creating package folder: {out_dir}")
    ensure_dir(out_dir)

    # Folder structure
    bin_dst = ensure_dir(os.path.join(out_dir, "Binaries"))
    content_dst = ensure_dir(os.path.join(out_dir, "Content"))
    config_dst = ensure_dir(os.path.join(out_dir, "Config"))
    logs_dst = ensure_dir(os.path.join(out_dir, "Logs"))

    # Copy executable
    shutil.copy2(os.path.join(binary_dir, exe), bin_dst)
    print(f"[COPY] {exe} -> Binaries/{plat}")

    # Copy local shared libraries from binary dir
    if plat == "Windows":
        for f in os.listdir(binary_dir):
            if f.lower().endswith(".dll"):
                src = os.path.join(binary_dir, f)
                shutil.copy2(src, bin_dst)
                print(f"[COPY] {f} (DLL)")

        # Ensure Vulkan loader is present
        bundle_windows_dependencies(bin_dst)

    elif plat in ("Linux", "FreeBSD"):
        for f in os.listdir(binary_dir):
            if ".so" in f or f.endswith(".dylib"):
                src = os.path.join(binary_dir, f)
                shutil.copy2(src, bin_dst)
                print(f"[COPY] {f} (local shared lib)")

        # Collect additional non-system .so libs via ldd
        exe_path = os.path.join(binary_dir, exe)
        collect_unix_shared_libs(exe_path, bin_dst)

    # ----------------------------------------------------------------------------------
    # Resolve asset and config folders (cross-platform)
    # ----------------------------------------------------------------------------------

    # Primary locations (inside binary dir)
    content_primary = os.path.join(binary_dir, "Content")
    config_primary = os.path.join(binary_dir, "Config")

    # Fallback locations (inside project-level build root)
    content_fallback = os.path.join(build_root, "Content")
    config_fallback = os.path.join(build_root, "Config")

    # --- CONTENT HANDLING (PLAIN or PACKED) ---

    if args.packed:
        # Still need to copy content first (to source for packing)
        if os.path.isdir(content_primary):
            copy_tree(content_primary, content_dst)
            source_for_packing = content_primary
        elif os.path.isdir(content_fallback):
            copy_tree(content_fallback, content_dst)
            source_for_packing = content_fallback
        else:
            print("[ERROR] No Content folder found — cannot pack assets.")
            return

        # Now replace loose assets with Pack.bin / Pack.json
        pack_assets(source_for_packing, content_dst, keep_plain=args.keep_plain)

    else:
        # Normal mode: plain content
        if os.path.isdir(content_primary):
            copy_tree(content_primary, content_dst)
        elif os.path.isdir(content_fallback):
            copy_tree(content_fallback, content_dst)
        else:
            print("[WARN] No Content folder found (neither Release/ nor Build root).")# --- CONTENT HANDLING (PLAIN or PACKED) ---

    # --- Config ---
    if os.path.isdir(config_primary):
        copy_tree(config_primary, config_dst)
    elif os.path.isdir(config_fallback):
        copy_tree(config_fallback, config_dst)
    else:
        print("[WARN] No Config folder found.")

    # Logs (empty)
    ensure_dir(logs_dst)

    # Write manifest
    write_manifest(out_dir, project_name, version, plat)

    # Create ZIP archive
    zip_path = shutil.make_archive(out_dir, "zip", out_dir)
    print(f"[OK] Archive created: {zip_path}")

    print("\n=============================================")
    print(" Packaging COMPLETE!")
    print(f" Output folder:\n   {out_dir}")
    print("=============================================")


if __name__ == "__main__":
    main()
